language: node_js
node_js: "node"
branches:
  only:
    - master
before_install: 
  - cd "Custom Right-Click Menu"
  - npm install grunt -g
install:
  - npm install
before_script:
  - cd "../"
script: sh ./build.sh
notifications:
  email:
    on-success: change
    on_failure: change
