language: node_js
node_js: "node"
branches:
  only:
    - master
before_install: 
  - cd "Custom Right-Click Menu"
  - npm install grunt -g
install:
  - ls 
  - npm install
after_install:
  - ls
  - cd "../"
  - ls
script: sh build.sh