language: node_js
node_js: "node"
branches:
  only:
    - master
before_install: 
  - cd "Custom Right-Click Menu"
  - npm install grunt -g
install: npm install
script:
  - grunt build
  - grunt cleanBuild
  - grunt extractDefs
  - grunt clean
  - grunt website
  - bash ./build.sh